### ISSUE TITLE
[REQUEST] Add The Xen-Project

### ISSUE THREAD

**Issue by dfaggioli** [SUSE/project-portal#12]
Necessary information:

**Project name**
The Xen-Project

**Project tag**
Infrastructure

**Project description**
The Xen-Project provides advanced, secure, flexible and performant virtualization solutions for Enterprises, for the Cloud, for the Embedded world, and more

**Project repository URL**
https://xenbits.xen.org/git-http/xen.git

**Comment by dfaggioli** [comment]
I wasn't sure between "Operating Systems" and "Infrastructure" for the category... I think the latter fits better (unless we create a "Virtualization" category, which can then host not only Xen, but also QEMU, KubeVirt, and maybe Harvester?)

**Comment by kwwii** [comment]
Adding a virtualization category does sound like a no-brainer, although this might possibly require re-categorization of the current projects. The category list was defined by product marketing so I would refer this to @vestival for a decision on this.

**Comment by en3sis** [comment]
Would the link be correct? Seems to be offline on my end.

**Comment by dirkmueller** [comment]
it appears the right link is https://xenbits.xen.org/gitweb/?p=xen.git;a=summary
