### ISSUE TITLE
[REQUEST] Add GCC to the open source projects list

### ISSUE THREAD

**Issue by jamborm** [SUSE/project-portal#14]
Necessary information:

**Project name**
GNU Compiler Collection (GCC)

**Project tag**
Development

**Project description**
Compilers of C/C++, Fortran, Ada, Go and other languages

**Project repository URL**
https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git

**Comment by en3sis** [comment]
Merged as part of https://github.com/SUSE/project-portal/pull/23.

Closing Issue.
