### ISSUE TITLE
[REQUEST] Add glibc to the list of open source projects

### ISSUE THREAD

**Issue by jamborm** [SUSE/project-portal#16]
Necessary information:

**Project name**
The GNU C Library (glibc)

**Project tag**
Operating Systems

**Project description**
The core system library of (not just) Linux systems

**Project repository URL**
https://sourceware.org/git/?p=glibc.git

**Comment by en3sis** [comment]
Merged as part of https://github.com/SUSE/project-portal/pull/23.

Closing Issue.
