### ISSUE TITLE
[REQUEST] Deployment of the SUSE Open Source policy update to gh-pages

### ISSUE THREAD

**Issue by lkocman** [SUSE/project-portal#43]
Necessary information:

I'd like to request to publish of the changes from #41 to gh-pages as nobody who's available seems to know that's the right workflow to deploy it properly to gh-pages :) 

PR contains latest changes from https://github.com/SUSE/open-source-policy

**Comment by lkocman** [comment]
Also we should most likely document this, unless it's very obvious for people with access.

**Comment by dirkmueller** [comment]
We are not using GitHub pages but a timed GitHub action for deployment.

**Comment by dirkmueller** [comment]
It should be online tomorrow, I can check how to do this manually but most people are patient enough to wait

**Comment by lkocman** [comment]
Tomorrow is good enough Dirk, I was afraid that it's fully manual. Thank you!

**Comment by dirkmueller** [comment]
It's fully automated on a different repository here:

https://github.com/SUSE/suse.github.io/blob/main/.github/workflows/gh-pages.deploy.yml

Apparently GitHub requires clicking a button every 60 days to keep time bases actions alive. I just clicked the button so the next deployment should have it.

I'll add a README when I am getting back at the computer.

**Comment by dirkmueller** [comment]
documentation is online at https://github.com/SUSE/suse.github.io/blob/main/README.md
